#lab 4
library(tidyverse)
load("aurelia_15minCell_statareas.Rdata")
save(a,file = "aurelia_15minCell_statareas.Rdata")
str(a)
b=read_csv(file = "aurelia_15minCell_statareas.txt")
str(b)
library(readxl)
c=read_xlsx("Aurelia_SEAMAP_2012-2018_30minCell.xlsx")
str(c)
d=read.csv("BGSREC.csv")
str(d)
e=read_csv("CRUISES.csv")
str(e)
f=read_csv("CTDCASTREC.csv")
str(f)
g=read_csv("CTDREC.csv")
str(g)
h=read_csv("ENVREC.csv")
str(h)
i=read_csv("GLFREC.csv")
str(i)
j=read_csv("INGEST_DATA.csv")
str(j)
k=read_csv("INVREC.csv")
str(k)
l=read.table('ISIIS201405281105.txt',sep = "\t",skip=10, header = TRUE, stringsAsFactors = FALSE,)
str(l)
m=read.table('ISIIS201405281124.txt',sep = "\t",skip=10, header = TRUE, fileEncoding = "ISO-8859-1", stringsAsFactors = FALSE, quote="\"", check.names = FALSE,na.strings = "9999.99")
str(m)
n=read.table('ISIIS201405281215.txt',sep = "\t",skip=10, header = TRUE, stringsAsFactors = FALSE,)
o=read.table('ISIIS201405281609.txt',sep = "\t",skip=10, header = TRUE, stringsAsFactors = FALSE,)
p=read_csv("ISTREC.csv")
str(p)
q=read_csv("lg_camera_class_groupings_20170113_phylo_orderd.csv")
str(q)
r=read_xlsx("NameTranslator_table20140330.xlsx")
str(r)
s=read_csv("NEWBIOCODESBIG.csv")
str(s)
t=read_csv("SHRREC.csv")
str(t)
u=read_csv("STAREC.csv")
str(u)
v=read_csv("STAREC_rev20190402.csv")
w=read_xlsx("transect_towtime.xlsx")
x=read_csv("VESSELS.csv")
